package com.sencloud.mybatis.dao;

import com.sencloud.mybatis.dataobject.DepartmentDO;

public interface DepartmentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Tue Jul 09 14:52:57 CST 2019
     */
    int deleteByPrimaryKey(Integer departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Tue Jul 09 14:52:57 CST 2019
     */
    int insert(DepartmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Tue Jul 09 14:52:57 CST 2019
     */
    int insertSelective(DepartmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Tue Jul 09 14:52:57 CST 2019
     */
    DepartmentDO selectByPrimaryKey(Integer departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Tue Jul 09 14:52:57 CST 2019
     */
    int updateByPrimaryKeySelective(DepartmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Tue Jul 09 14:52:57 CST 2019
     */
    int updateByPrimaryKey(DepartmentDO record);


    DepartmentDO findDeptByIdPlus(Integer id);

}