package com.sencloud.mybatis.dao;

import com.github.pagehelper.Page;
import com.github.pagehelper.PageInfo;
import com.sencloud.mybatis.dataobject.EmployeeDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EmployeeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Jul 08 14:48:43 CST 2019
     */
    int deleteByPrimaryKey(Integer employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Jul 08 14:48:43 CST 2019
     */
    int insert(EmployeeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Jul 08 14:48:43 CST 2019
     */
    int insertSelective(EmployeeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Jul 08 14:48:43 CST 2019
     */
    EmployeeDO selectByPrimaryKey(Integer employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Jul 08 14:48:43 CST 2019
     */
    int updateByPrimaryKeySelective(EmployeeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Jul 08 14:48:43 CST 2019
     */
    int updateByPrimaryKey(EmployeeDO record);

    /**
     * 分页
     *
     * @return
     */
    List<EmployeeDO> findByPage();

    /**
     * 搜索条件加分页
     */
    List<EmployeeDO> findByNameForPage(String firstName);

    /**
     * 根据员工id查询emp和dept
     */
    EmployeeDO findEmpAndDept(Integer id);

    /**
     * 遍历集合
     *
     * @param list
     * @return
     */
    List<EmployeeDO> getEmpByIds(@Param("list") List<Integer> list);

    /**
     * 批量保存
     *
     * @param employeeDOList
     */
    void addEmps(@Param("emps") List<EmployeeDO> employeeDOList);

    /**
     * 批量删除
     * @param empIds
     */
    void deleteEmps(@Param("empsDelList") List<Integer> empIds);
}